steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chatieee-backend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chatieee-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chatieee-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/chatieee-backend'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'firebase-adminsdk-fbsvc@chat-ieee.iam.gserviceaccount.com'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '20'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '100'
      - '--update-env-vars'
      - '^#^EMBEDDING_MODEL=text-embedding-3-small#ANSWER_MODEL=gpt-5-mini#DEFAULT_VERBOSITY=high#FIREBASE_ADMIN_CREDS=.secrets/FIREBASE_ADMIN_CREDS#FIREBASE_ADMIN_CREDS=/.secrets/FIREBASE_ADMIN_CREDS'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest,DATABASE_URL=DATABASE_URL:latest,/.secrets/FIREBASE_ADMIN_CREDS=FIREBASE_ADMIN_CREDS:latest'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/chatieee-backend'

  # Service account configuration
serviceAccount: 'projects/chat-ieee/serviceAccounts/firebase-adminsdk-fbsvc@chat-ieee.iam.gserviceaccount.com'

# Build options
options:
  logging: 'CLOUD_LOGGING_ONLY'
  substitutionOption: 'ALLOW_LOOSE'
  diskSizeGb: '100'

# Timeout for the entire build
timeout: '1800s'
